[package]
name = "bevy_fbx"
version = "0.1.0-dev"
edition = "2021"
repository = "https://github.com/HeavyRain266/bevy_fbx"
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]
description = "Autodesl Filmbox (*.fbx) scene loader for Bevy Engine"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "bevy_plugin", "fbx_loader"]

[dependencies]
rgb = "0.8.33"
image = "0.24.2"
anyhow = "1.0.58"
glam = { version = "0.20", features = ["mint"] }
fbxcel-dom = "0.0.8"

[dependencies.bevy]
version = "0.7.0"
default-features = false
features = [
  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  # "bevy_core_pipeline"
]

[[example]]
name = "scene_viewer"
path = "examples/scene_viewer.rs"

[dev-dependencies]
bevy-inspector-egui = "0.11"

[dev-dependencies.bevy]
version = "0.7.0"
default-features = false
features = [
  "x11", #"wayland",

  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  "filesystem_watcher",
  "bevy_core_pipeline"
]
